### ISSUE TITLE
Different constant in the reward function of Humanoid w.r.t the original Humanoid

### ISSUE THREAD

**Issue by wjaskowski** [JannerM/mbpo#21]
Compare two lines:
https://github.com/JannerM/mbpo/blob/49587a1b0b4e91f8068009e0727c71bc68d904f2/mbpo/env/humanoid.py#L37 vs. https://github.com/openai/gym/blob/8cf2685db25572e4fd6716565694d05f83000d60/gym/envs/mujoco/humanoid.py#L30

**Comment by JannerM** [comment]
This was changed in OpenAI gym in the most recent update to humanoid ([commit link](https://github.com/openai/gym/commit/8797474abd532b6a95c3b4ca73be494830d930f1)). If I understand the commit correctly, the new coefficient would actually increase returns. I'm not completely sure why it was changed, but I think I'm going to keep the old version of the environment in this repo so that the results remain comparable to previously published work.

**Comment by wjaskowski** [comment]
Ah. I see. It might be that given that also the `dt` has changed, the net result is the same (vide https://github.com/openai/gym/issues/1380)
