### ISSUE TITLE
Observations in Ant and Humanoid env

### ISSUE THREAD

**Issue by VuongLong** [JannerM/mbpo#3]
Dear author,

Could you explain the reason why some values in observation are ignored in Ant and Humanoid environments in comparison to original environment from openAI Gym.
https://github.com/JannerM/mbpo/blob/master/mbpo/env/ant.py
https://github.com/JannerM/mbpo/blob/master/mbpo/env/humanoid.py

Thank you so much!

**Comment by JannerM** [comment]
MuJoCo environments are deterministic given `qpos` and `qvel`, so any other information is in principle not needed. Since including the contact forces makes the prediction problem harder for no real benefit, it is easiest to just ignore those values.

Even though [`qpos` is not fully observed](https://github.com/JannerM/mbpo/blob/master/mbpo/env/ant.py#L33), like in the usual benchmarks, the same idea holds true.
